### ISSUE TITLE
Cambio de escenarios

### ISSUE THREAD

**Issue by RicardoGuevara** [RicardoGuevara/Pedestrian-Behaviour#13]
Cambio de un escenario a otro:

La propuesta de selección de escenarios previo a la carga (por menú) ha sido descartada por ser poco práctica y sobre saturada de información.

La idea ahora es realizar el cambio de escenarios de forma secuencial usando los controles de las Gear-vr (que emulan los controles de volumen del celular).

Posteriormente, al añadir fuentes de sonido al proyecto habría que compensar los cambios que puedan hacerse desde los controles.

Recibo ideas de opciones alternas para el cambio de escenarios.

Nota: el Gear-vr deja espacio suficiente a costado del celular para conectar auriculares, por lo cual esto no representara un problema a la hora de insertar fuentes de sonido.

**Comment by vrlls** [comment]
Una opción podría ser no incluir la elección de escenario sino el cambio automático de estos cuando el usuario termina una simulación, suponiendo que esto esto podría saturar menos el programa y agilizar las cosas.

**Comment by RicardoGuevara** [comment]
> Una opción podría ser no incluir la elección de escenario sino el cambio automático de estos cuando el usuario termina una simulación, suponiendo que esto esto podría saturar menos el programa y agilizar las cosas.

No podemos saber cuanto tardará una persona en cada escenario, es decir, observando todo el entorno y respondiendo sus preguntas de la encuesta

**Comment by Juandavid716** [comment]
Puede ser algo poco estético, sin embargo, se podría añadir una especie de valla informativa, la cual, configurando con el controlador del gear - vr permita presionar un botón sobre esta, que de paso a cargar una nueva escena. El punto es que se le tendría que decir a la persona que no oprima el botón hasta que finalice la escena. El problema es que seria el usuario quien tiene la disposición de cambiar de escenario y no nosotros como los que administramos la prueba.

**Comment by jestrade** [comment]
Yo creo que la persona debe hacer una pausa cada cambio de escenario para que se le pueda realizar la encuesta. Esta pausa serviría para cambiar de app en el celular, y para que no se fatigue. Igual hay que validarlo con Luis.

**Comment by RicardoGuevara** [comment]
PROVISIONAL: los escenarios se encuentran ordenados en una cola de ejecución, el cambio se realiza de una escena a otra al observar una plataforma bajo la cámara durante un tiempo determinado
( adjunto la documentación necesaria en el readme interno de comportamiento peatonal )
