### ISSUE TITLE
Detección de colisiones en modelos complejos

### ISSUE THREAD

**Issue by RicardoGuevara** [RicardoGuevara/Pedestrian-Behaviour#4]
**Box colliders en modelos complejos**
en la escena principal (untitled) la pared de eliminación no detecta las colisiones con objetos complejos (autos/personas) que poseen box o mesh colliders.

**Comment by RicardoGuevara** [comment]
new issue

**Comment by Juandavid716** [comment]
el problema ha sido solucionado utilizando un rigidbody en los objetos a colisionar, teniendo en cuenta tener activadas las opciones Convex y Receive Shadows en los mesh colliders.
